In [1]:

import tensorflow as tf 


2024-09-05 23:48:43.922595: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-05 23:48:44.140002: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-05 23:48:44.262133: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-05 23:48:44.515474: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-05 23:48:44.591142: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-05 23:48:45.054720: I tensorflow/core/platform/cpu_feature_gu

<br>

# 1.1 `Read image file :` 

<br>

In [8]:

# image/* means: we read all the foder and file in image folder: 

image_ds = tf.data.Dataset.list_files('images/*',shuffle=False)

for i in image_ds:
    print(i)

tf.Tensor(b'images/cat', shape=(), dtype=string)
tf.Tensor(b'images/dog', shape=(), dtype=string)
tf.Tensor(b'images/temp.txt', shape=(), dtype=string)


In [23]:

# image/*/* because, In image folder we have two more folder(cat,dog)
# in those(cat,dog) folder, we have file. 

image_ds = tf.data.Dataset.list_files('images/*/*',shuffle=False)

for i in image_ds:
    print(i.numpy())

b'images/cat/20 Reasons Why Cats Make the Best Pets....jpg'
b'images/cat/7 Foods Your Cat Can_t Eat.jpg'
b'images/cat/A cat appears to have caught the....jpg'
b'images/cat/Adopt-A-Cat Month\xc2\xae - American Humane....jpg'
b'images/cat/All About Your Cat_s Tongue.jpg'
b'images/cat/Alley Cat Allies _ An Advocacy....jpg'
b'images/cat/Are Cats Domesticated_ _ The New Yorker.jpg'
b'images/cat/Cat Advice _ Collecting a Urine Sample....jpg'
b'images/cat/Cat Throwing Up_ Normal or Cause for....jpg'
b'images/cat/Cat intelligence - Wikipedia.jpg'
b'images/cat/Cats Care About People More Than Food....jpg'
b'images/cat/Cats _ The Humane Society of the United....jpg'
b'images/cat/Cats really do need their humans_ even....jpg'
b'images/cat/China_s First Cloned Kitten_ Garlic....png'
b'images/cat/Famous Cat Performances in Movies_ Ranked.jpg'
b'images/cat/Giving cats food with an antibody may....jpg'
b'images/cat/Home_ sweet home_ How to bring an....jpg'
b'images/cat/How to Determine Your Cat_s Age


<br>

# 1.2 `Count: total number of image:` 

<br>

In [13]:

total_img_length = len(image_ds)
total_img_length


130

<br>

# 1.3 `Train_Test_Split: `

- In sk-learn we have `train_test_split()`.
- But for tensorflow we have no inbuid function but we use `.take()`. 

<br>

In [17]:

# training data set we have: 130*0.8 = 104 images for traning : 
train_size = int(total_img_length * 0.8)

train_ds = image_ds.take(train_size)
test_ds = image_ds.skip(train_size)

# print the length of train_ds and test_ds:

print("length of train_ds: {}".format(len(train_ds)))
print(f"length of test_ds {len(test_ds)}")

length of train_ds: 104
length of test_ds 26


<br>

# 1.4 `How to find the label.`

- For classification problem. We need the level either in the photo we have dog or cat.

<br>

In [18]:

# let's take an example : 

s = "images/cat/20 Reasons Why Cats Make the Best Pets....jpg"

s.split('/')


['images', 'cat', '20 Reasons Why Cats Make the Best Pets....jpg']

In [20]:

# from the end side: -2 is the index of "label"
s.split('/')[-2]

'cat'

In [30]:

# This will give us an error: cause tensor string and normal python string is not same . 
# Solution: we need use tensor strings. 

def getLevelTest(path):
    return path.split('/')[-2]

for i in image_ds: 
    print(getLevelTest(i.numpy()))
    


TypeError: a bytes-like object is required, not 'str'


<br>
<br>

## First,  let know about string path difference in linux and windows  operating system. 


`os.path.sep` is a string attribute in Python that represents the operating system's directory separator (such as `/` on Unix-like systems, including Linux and macOS, and `\` on Windows).

It helps when you need to write cross-platform code that deals with file paths, ensuring that you use the correct directory separator for the operating system your code is running on.

### Output:
- **On Unix-like systems**: `user/documents/file.txt`
- **On Windows**: `user\documents\file.txt`

Using `os.path.sep` ensures your code handles file paths correctly across different operating systems.

<br>
<br>

In [29]:

def getLevel(path):
    import os
    return tf.strings.split(path,os.path.sep)[-2]

for i in image_ds: 
    print(getLevel(i))
    print(getLevel(i).numpy())
    print()
    

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'

tf.Tensor(b'cat', shape=(), dtype=string)
b'cat'



In [37]:

# we can also use map function : 

for i in train_ds.map(getLevel):
    print(i.numpy())
    
    

b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'
b'dog'



<br>

# 1.5 `Prepare Traning data:`

- In our train data we have input and output.
- For image: in `X_train` it should be image.
- For image: in `Y_train` it should be label.



<br>

In [33]:

def process_image(file_path):
    lebel = getLevel(file_path)
    # tf.io.read_file() this function store the image:
    img = tf.io.read_file(file_path)
    # our image is jpeg we need to decode it.
    img = tf.io.decode_jpeg(img)
    # image should be different dimention we reduce the dimention of the image
    img = tf.image.resize(img,[128,128])
    return img, lebel


In [39]:


for image,level in train_ds.map(process_image).take(3):
    print(f"image: {image}")
    print(f"Lebel: {level}")
    


image: [[[155.       186.       215.      ]
  [156.       187.       216.      ]
  [158.       189.       218.      ]
  ...
  [ 90.99609   84.99609   72.99609 ]
  [ 92.        86.        74.      ]
  [ 93.        87.        75.      ]]

 [[156.01172  187.01172  216.01172 ]
  [157.02344  188.02344  217.02344 ]
  [159.01172  190.01172  219.01172 ]
  ...
  [ 86.98828   82.97656   74.01172 ]
  [ 89.97656   85.96484   77.      ]
  [ 91.        86.98828   78.02344 ]]

 [[159.       190.       219.      ]
  [160.       191.       220.      ]
  [161.01953  192.01953  221.01953 ]
  ...
  [ 80.96094   77.96094   72.96094 ]
  [ 85.        82.        77.      ]
  [ 87.        84.        79.      ]]

 ...

 [[ 91.09766   44.98047   73.17578 ]
  [108.25781   83.16016   86.25781 ]
  [ 36.058594  33.058594  18.058594]
  ...
  [ 51.234375  32.214844  34.195312]
  [ 41.078125  18.078125  26.078125]
  [ 38.941406  24.941406  23.941406]]

 [[141.90625  123.88281  111.91797 ]
  [ 69.91797   58.89453   40.9


<br>

# 1.6 `Scaling: in our train data set: `

<br>


In [40]:

def scaling(image,level):
    return image/255,level


In [45]:

df_train = train_ds.map(process_image).map(scaling)

for image,level in df_train.take(5):
    print(image[0][0])
    print(level)
    print()


tf.Tensor([0.60784316 0.7294118  0.84313726], shape=(3,), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)

tf.Tensor([0.6878983  0.69181985 0.672212  ], shape=(3,), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)

tf.Tensor([0.7736826  0.8089767  0.79120713], shape=(3,), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)

tf.Tensor([0.38330558 0.6778809  0.3122568 ], shape=(3,), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)

tf.Tensor([0.03924632 0.07846201 0.04316789], shape=(3,), dtype=float32)
tf.Tensor(b'cat', shape=(), dtype=string)

